### PR TITLE
Readme: change param name in callbacks

### PR DESCRIPTION
**Pull request by drzamich**
Rename `x` to `input` for better example code readability.

### CODE REVIEW

**Comment by drzamich** [comment]
@daattali I was also thinking abut simplifying `if` statements in lines `229` and `230`
```diff
-      callbackR = function(input) { if(input != FALSE) message("Hello ", input) },
+      callbackR = function(input) { if(input) message("Hello ", input) },
```
```diff
-      callbackJS = "function(input) { if (input !== false) { alert('Hello ' + input); } }"
+      callbackJS = "function(input) { if (input) { alert('Hello ' + input); } }"
```

**Comment by daattali** [comment]
I agree `x` is not great. But I would not use `input`, since that would override the `input` that the server function already has defined. Let's use something that isn't already defined.

Regarding the if statements: I prefer to be explicit

**Comment by drzamich** [comment]
I changed the param name from `input` to `response`. What do you think about that, @daattali?

**Comment by daattali** [comment]
Great choice. It looks like you missed a couple places where input is still used

**Comment by drzamich** [comment]
Right, I totally overlooked it! Should be fine now. I also changed `value` to `response` in yet another example to have consistency throughout the whole Readme.

**Comment by daattali** [comment]
Thanks, looks good. I forgot to mention before that the README is actually generated from the Rmd in the vignettes folder, so these changes need to be reverted and they need to be made in that vignette instead. Sorry for not bringing this up before!

**Comment by daattali** [comment]
@drzamich do you want to finish this PR?

**Comment by drzamich** [comment]
@daattali yes, sorry, it completely slipped my mind. I will finish it in the upcoming days

**Comment by drzamich** [comment]
Have to abandon this due to lack of time.

**Pull request closed without merging**
