### PR TITLE
Incorporate the changes in PR 30,32 to fix issues 29,31

### PR DESCRIPTION
**Pull request by daattali**

### CODE REVIEW

**Comment by dipterix** [comment]
I see. I tried the branch `feature-close` in your repository and it passed on all of my test cases.

I merged your previous PR into my forked repository and the branch somehow doesn't work. Please don't use PR #30

**Comment by daattali** [comment]
"your previous PR" you mean PR #30 the one that you made? 

This (#37) is **my** only PR. This looks good to merge?

**Comment by dipterix** [comment]
Right to both. 

Previous #30 is not working right now. Your PR #37 works on my cases.

**Comment by daattali** [comment]
So this still leaves one unresolved issue.

```
library(shiny)

ui <- fluidPage(
    shinyalert::useShinyalert(),
    actionButton('test', 'test')
)

server <- function(input, output, session) {
    observeEvent(input$test, {
        shinyalert::shinyalert("modal 1",
                               timer = 1000,
                               callbackR = function() {
                                   shinyalert::shinyalert("modal 2")
                               })
        
    })
}

shinyApp(ui, server)
```

This bug still happens - a callback in a timer doesn't show an alert. Any idea?

**Comment by daattali** [comment]
Actually, looks like `callbackR` just doesn't work together with a timer, that's the issue

**Comment by dipterix** [comment]
If I remember correctly, that was one of the reason I use `closeAndFireCallback` instead of `close`. (Please double check this)

`close` just closes the alert. callbacks will not fire. `closeAndFireCallback` suppose to file callbacks

**Comment by dipterix** [comment]
However, `closeAndFireCallback` has wrong implementation in your original package.

If you look at my original modification, I made these changes.

### After modification

https://github.com/dipterix/shinyalert/blob/839117e8b5b17af1e767232d9dc13f7def9a15ec/inst/www/shared/swalservice/swalservice.js#L88

### Before modification

https://github.com/dipterix/shinyalert/blob/66b430ef12ef93eb7e6c9d8ec8f010f9e869e66c/inst/www/shared/swalservice/swalservice.js#L88

**Comment by daattali** [comment]
Yeah this is what my previous comment was talking about: https://github.com/daattali/shinyalert/pull/37#issuecomment-689043343

When I added the closeAndFireCallback, I was no longer able to have two consecutive alerts where the second has a timer.

**Comment by dipterix** [comment]
I went back trying the original proposal (https://github.com/dipterix/shinyalert/tree/bug1_fix). Everything worked fine in all these cases, including the issue on not able to close the second alert. 

One thing very important is in my branch, I changed your 
* inst/www/shared/swalService/swalService.js
* function `useShinyalert` line 53 from `swalservice.min.js` to `swalservice.js`

It it possible that you were actually using `swalservice.min.js` instead of my modified `swalservice.js` when merging th code?

**Comment by daattali** [comment]
I did make those changes. I added them in a new branch so you can test: https://github.com/daattali/shinyalert/tree/bug31fix (that branch has one more commit on top of this PR)

The following code does not work, you cannot dismiss the first alert:

```
library(shiny)

ui <- fluidPage(
    shinyalert::useShinyalert(),
    actionButton('test', 'test')
)

server <- function(input, output, session) {
    observeEvent(input$test, {
        shinyalert::shinyalert("modal 1")
        shinyalert::shinyalert("modal 2", timer = 1000)
    })
}

shinyApp(ui, server)
```

**Comment by daattali** [comment]
Found the issue. All is fixed now. Thanks for your help!

**Pull request merged**
